### ISSUE TITLE
Bug en el sistema de opciones

### ISSUE THREAD

**Issue by mlaina** [Victorma/Puppeteer#1]
En el ISO al configurar varios nodos de opciones, o repetir un mismo nodo de éste tipo, al mostrarlo en pantalla se acumulan las opciones de nodos anteriores dentro de una misma escena, y no se eliminan las opciones anteriores. Acumulando así muchos botones en una sola pantalla.

**Comment by Victorma** [comment]
Debería estar resuelto en el último commit. Lo reviso y te cuento

**Comment by Victorma** [comment]
Se resolvió en https://github.com/Victorma/isometra-dialog-system/commit/8ac1a2137b6d13671a4a079a121a478c64a8fd6e
